[workspace]
# Enable Git tags creation (defaults to v<version>, e.g., v0.1.1)
git_tag_enable = true

# Publish releases directly to crates.io
publish = true

# Release commit message format (chore)
git_release_commit = "chore: release {{ package }} version {{ version }}"
